apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  # admin / password123
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
  MONGO_INITDB_DATABASE: YWRtaW4=
---
apiVersion: v1
kind: Secret
metadata:
  name: app-config-secret
  namespace: default
type: Opaque
data:
  # Database URLs and connection strings
  MONGODB_URL: bW9uZ29kYjovL2FkbWluOnBhc3N3b3JkMTIzQG1vbmdvZGItc2VydmljZToyNzAxNy9QUlVFQkE/YXV0aFNvdXJjZT1hZG1pbg==