{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}-mongodb
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: mongodb
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mongodb
  template:
    metadata:
      labels:
        {{- include "helm.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mongodb
    spec:
      containers:
        - name: mongodb
          image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
          imagePullPolicy: {{ .Values.mongodb.image.pullPolicy }}
          ports:
            - name: mongodb
              containerPort: 27017
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-mongodb-secret
                  key: mongodb-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "helm.fullname" . }}-mongodb-secret
                  key: mongodb-root-password
            - name: MONGO_INITDB_DATABASE
              value: "PRUEBA"
          volumeMounts:
            - name: mongodb-init
              mountPath: /docker-entrypoint-initdb.d
          resources:
            {{- toYaml .Values.mongodb.resources | nindent 12 }}
      volumes:
        - name: mongodb-init
          configMap:
            name: {{ include "helm.fullname" . }}-mongodb-init
{{- end }}