global:
  namespace: default

redis:
  enabled: true
  replicaCount: 1
  image:
    repository: redis
    tag: "7-alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

redisService:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost/redis-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8082
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

readService:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost/read-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8081
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

writeService:
  enabled: true
  replicaCount: 1
  image:
    repository: localhost/write-service
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

mongodb:
  enabled: true
  replicaCount: 1
  image:
    repository: mongo
    tag: "5.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 27017
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi